services:
  # device_agent:
  #   image: spaneng/doover_device_agent:apps
  #   network_mode: host

  # sample_simulator:
  #   build: ./sample
  #   network_mode: host
  #   restart: unless-stopped
  #   depends_on:
  #     - device_agent
  #   environment:
  #     - APP_KEY=sim_app_key

  local_ui_application:
    build: ../
    network_mode: host
    restart: unless-stopped
    # depends_on:
    #   - device_agent
    #   - sample_simulator
    environment:
      - APP_KEY=sia_local_control_ui-1
